b:
	/bin/bash back.sh
t:
	/bin/bash test.sh
u:
	cd github && /bin/bash update.sh
uf:
	cd github && /bin/bash update.sh force
c:
	ls -la knex-prototype/node_modules/ | grep knex-prototype
h:
	@echo https://github.com/tomekwlod/knex-prototype
islinked:
	@ls -la knex-prototype/node_modules/ | grep knex-prototype
unlink:
	/bin/bash github/dev/unlink.sh

