b:
	/bin/bash back.sh
t:
	/bin/bash test.sh
u:
	cd github && /bin/bash update.sh
uf:
	cd github && /bin/bash update.sh force
c:
	ls -la knex-abstract/node_modules/ | grep knex-abstract
h:
	@echo https://github.com/tomekwlod/knex-abstract
islinked:
	@ls -la knex-abstract/node_modules/ | grep knex-abstract
unlink:
	/bin/bash github/dev/unlink.sh

