version: '3.1'

services:
    mysql:
        container_name: knex-proto-mysql
        image: mysql/mysql-server:5.7
        ports:
            - "1060:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=docker_super_secret_passwd
            - MYSQL_ROOT_HOST=%
        volumes:
            - ./mysql:/var/lib/mysql
    postgres:
        container_name: knex-proto-postgres
        image: postgres:9.6.20
        ports:
            - 1061:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: knex
        volumes:
            - ./postgres:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.30
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "password"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        ports:
            - "1062:80"
#        restart: unless-stopped