name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Prepare package.json
        run: make ct
      - name: Prepare .env
        run: cp .env.dist .env
      - name: nodemon global
        run: npm install --global nodemon