name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services: # https://github.com/actions/example-services/actions/runs/449599975/workflow
      mysql:
        image: mysql/mysql-server:8.0.27
        env:
          MYSQL_DATABASE: knex
#          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: docker_super_secret_passwd
          MYSQL_ROOT_HOST: '%'
        ports:
          - 4238:3306
        # needed because the mysql container does not provide a healthcheck
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idoptions
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10 --name=mysql
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Prepare package.json
        run: make ct
      - name: Prepare .env
        run: cp .env.dist .env
      - name: Yarn install
        run: yarn install
      - name: Knex link
        run: make link
      - name: Setup migration config
        run: cp migrations/ormconfig.js.mysql migrations/ormconfig.js
      - name: MySQL healtly?
        run: docker ps
      - name: MySQL fixtures
        run: make fixtures
      - name: test mysql
        run: /bin/bash test.sh test/knex/mysql