name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Prepare package.json
        run: make ct
      - name: Prepare .env
        run: cp .env.dist .env
      - name: Yarn install
        run: yarn install
      - name: Knex link
        run: make link
      - name: Setup migration config
        run: cp migrations/ormconfig.js.mysql migrations/ormconfig.js
      - uses: mirromutth/mysql-action@v1.1 # https://github.com/marketplace/actions/setup-mysql#the-default-mysql
        with:
          host port: 4238 # Optional, default value is 3306. The port of host
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0.27' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'knex' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'docker_super_secret_passwd' # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: MySQL fixtures
        run: make fixtures
      - name: test mysql
        run: /bin/bash test.sh test/knex/mysql